import type { DashboardRun } from "@/lib/types";

export const mockRuns: DashboardRun[] = [
  {
    userId: "demo-user",
    jobId: "run_langchain_bootstrap",
    repoName: "langchain-ai/langchain",
    repoUrl: "https://github.com/langchain-ai/langchain",
    query: "Map architecture and explain runnable entry points",
    intent: "mixed",
    status: "completed",
    currentNode: null,
    finalOutput: "Architecture overview and entry evidence completed.",
    error: null,
    partialSummaries: {
      architect_mapper: "Framework and package boundary evidence collected.",
      entry_explainer: "Runnable entry path evidence collected.",
      verifier: "Three high-risk claims verified against focused tests.",
    },
    errors: [],
    userCorrections: [],
    verifiedCount: 0,
    unverifiedCount: 0,
    contradictedCount: 0,
    claimProvenance: [],
    traceMetadata: {
      agent_name: "architect_mapper",
      tool_name: "repo_structure",
      mcp_server: "repo_mapper",
      latency: 4.2,
      tokens: 0,
      cost_usd: 0,
      claim_id: null,
    },
    agentName: "architect_mapper",
    toolName: "repo_structure",
    mcpServer: "repo_mapper",
    latency: 4.2,
    tokens: 0,
    costUsd: 0,
    failureModes: [],
    traceUrl: "https://smith.langchain.com/",
    createdAt: "2026-06-04T17:00:00Z",
    updatedAt: "2026-06-04T17:00:04Z",
  },
  {
    userId: "demo-user",
    jobId: "run_fixture_architecture",
    repoName: "fixture/python-service",
    repoUrl: "local://fixture/python-service",
    query: "Explain app.service.create_user behavior",
    intent: "architectural",
    status: "completed",
    currentNode: null,
    finalOutput: "AST evidence and verifier summary completed.",
    error: null,
    partialSummaries: {
      entry_explainer: "Definition, signature, references, and call-chain evidence collected.",
      verifier: "Two claims verified and one left unverified due no coverage.",
    },
    errors: [{ node: "verifier", errorType: "no_test_coverage", message: "No direct test target", retryable: false }],
    userCorrections: ["intent=behavioral"],
    verifiedCount: 2,
    unverifiedCount: 1,
    contradictedCount: 0,
    claimProvenance: [],
    traceMetadata: {
      agent_name: "entry_explainer",
      tool_name: "find_references",
      mcp_server: "ast_explorer",
      latency: 3.1,
      tokens: 0,
      cost_usd: 0,
      claim_id: "claim-0",
    },
    agentName: "entry_explainer",
    toolName: "find_references",
    mcpServer: "ast_explorer",
    latency: 3.1,
    tokens: 0,
    costUsd: 0,
    failureModes: ["no_test_coverage"],
    traceUrl: "https://smith.langchain.com/",
    createdAt: "2026-06-04T16:51:00Z",
    updatedAt: "2026-06-04T16:51:03Z",
  },
  {
    userId: "demo-user",
    jobId: "run_verifier_timeout",
    repoName: "fixture/slow-tests",
    repoUrl: "local://fixture/slow-tests",
    query: "Check retry behavior for timeout handling",
    intent: "debug",
    status: "completed",
    currentNode: null,
    finalOutput: "Timeout retried once, then the claim stayed unverified.",
    error: null,
    partialSummaries: { verifier: "Validation timed out after retry." },
    errors: [{ node: "verifier", errorType: "validation_timed_out", message: "Test timed out after retry", retryable: true }],
    userCorrections: [],
    verifiedCount: 1,
    unverifiedCount: 2,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "verifier", tool_name: "run_pytest", mcp_server: "test_runner", latency: 8.9, tokens: 0, cost_usd: 0, claim_id: "claim-timeout" },
    agentName: "verifier",
    toolName: "run_pytest",
    mcpServer: "test_runner",
    latency: 8.9,
    tokens: 0,
    costUsd: 0,
    failureModes: ["validation_timed_out"],
    createdAt: "2026-06-04T16:40:00Z",
    updatedAt: "2026-06-04T16:40:09Z",
  },
  {
    userId: "demo-user",
    jobId: "run_ast_missing_symbol",
    repoName: "fixture/api-service",
    repoUrl: "local://fixture/api-service",
    query: "Explain missing symbol UserService.create",
    intent: "behavioral",
    status: "completed",
    currentNode: null,
    finalOutput: "Missing symbol rejected by AST validation gate.",
    error: null,
    partialSummaries: { entry_explainer: "Symbol was not found; final output preserves the limitation." },
    errors: [{ node: "entry_explainer", errorType: "missing_symbol", message: "Symbol not present in parsed AST", retryable: false }],
    userCorrections: [],
    verifiedCount: 0,
    unverifiedCount: 1,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "entry_explainer", tool_name: "find_definition", mcp_server: "ast_explorer", latency: 2.4, tokens: 0, cost_usd: 0, claim_id: null },
    agentName: "entry_explainer",
    toolName: "find_definition",
    mcpServer: "ast_explorer",
    latency: 2.4,
    tokens: 0,
    costUsd: 0,
    failureModes: ["missing_symbol"],
    createdAt: "2026-06-04T16:30:00Z",
    updatedAt: "2026-06-04T16:30:02Z",
  },
  {
    userId: "demo-user",
    jobId: "run_route_correction",
    repoName: "fixture/routing",
    repoUrl: "local://fixture/routing",
    query: "Map this repo\n\nUser correction: intent=behavioral",
    intent: "behavioral",
    status: "completed",
    currentNode: null,
    finalOutput: "Refine resumed on the same thread with behavioral intent.",
    error: null,
    partialSummaries: { supervisor: "Accepted user route correction." },
    errors: [],
    userCorrections: ["intent=behavioral"],
    verifiedCount: 0,
    unverifiedCount: 0,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "entry_explainer", tool_name: "call_chain", mcp_server: "ast_explorer", latency: 1.8, tokens: 0, cost_usd: 0, claim_id: null },
    agentName: "entry_explainer",
    toolName: "call_chain",
    mcpServer: "ast_explorer",
    latency: 1.8,
    tokens: 0,
    costUsd: 0,
    failureModes: [],
    createdAt: "2026-06-04T16:20:00Z",
    updatedAt: "2026-06-04T16:20:02Z",
  },
  {
    userId: "demo-user",
    jobId: "run_unsupported_language",
    repoName: "fixture/typescript-lib",
    repoUrl: "local://fixture/typescript-lib",
    query: "Explain TypeScript class behavior",
    intent: "behavioral",
    status: "completed",
    currentNode: null,
    finalOutput: "TypeScript AST backend is unsupported in v1; output is degraded.",
    error: null,
    partialSummaries: { entry_explainer: "Unsupported language limitation surfaced." },
    errors: [{ node: "entry_explainer", errorType: "unsupported_language", message: "TypeScript backend not implemented", retryable: false }],
    userCorrections: [],
    verifiedCount: 0,
    unverifiedCount: 2,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "entry_explainer", tool_name: "find_definition", mcp_server: "ast_explorer", latency: 2.2, tokens: 0, cost_usd: 0, claim_id: null },
    agentName: "entry_explainer",
    toolName: "find_definition",
    mcpServer: "ast_explorer",
    latency: 2.2,
    tokens: 0,
    costUsd: 0,
    failureModes: ["unsupported_language"],
    createdAt: "2026-06-04T16:10:00Z",
    updatedAt: "2026-06-04T16:10:02Z",
  },
  {
    userId: "demo-user",
    jobId: "run_contradicted_claim",
    repoName: "fixture/payments",
    repoUrl: "local://fixture/payments",
    query: "Verify retry count behavior",
    intent: "runtime",
    status: "completed",
    currentNode: null,
    finalOutput: "One retry-count claim was contradicted and removed from final prose.",
    error: null,
    partialSummaries: { verifier: "One selected test contradicted a runtime claim.", reflection: "Unsafe claim removed." },
    errors: [],
    userCorrections: [],
    verifiedCount: 2,
    unverifiedCount: 0,
    contradictedCount: 1,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "verifier", tool_name: "run_single_test", mcp_server: "test_runner", latency: 5.6, tokens: 0, cost_usd: 0, claim_id: "test-payments-retry" },
    agentName: "verifier",
    toolName: "run_single_test",
    mcpServer: "test_runner",
    latency: 5.6,
    tokens: 0,
    costUsd: 0,
    failureModes: ["contradicted_claim"],
    createdAt: "2026-06-04T16:00:00Z",
    updatedAt: "2026-06-04T16:00:06Z",
  },
  {
    userId: "demo-user",
    jobId: "run_repo_too_large",
    repoName: "fixture/monorepo",
    repoUrl: "local://fixture/monorepo",
    query: "Map full monorepo architecture",
    intent: "architectural",
    status: "completed",
    currentNode: null,
    finalOutput: "Repo exceeded file-count policy; sampled architecture limitation shown.",
    error: null,
    partialSummaries: { architect_mapper: "Sampling proposal required for repo over 10000 files." },
    errors: [{ node: "architect_mapper", errorType: "repo_too_large", message: "Repo has more than 10000 files", retryable: false }],
    userCorrections: [],
    verifiedCount: 0,
    unverifiedCount: 1,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "architect_mapper", tool_name: "scan_repo", mcp_server: "repo_mapper", latency: 7.4, tokens: 0, cost_usd: 0, claim_id: null },
    agentName: "architect_mapper",
    toolName: "scan_repo",
    mcpServer: "repo_mapper",
    latency: 7.4,
    tokens: 0,
    costUsd: 0,
    failureModes: ["repo_too_large"],
    createdAt: "2026-06-04T15:50:00Z",
    updatedAt: "2026-06-04T15:50:07Z",
  },
  {
    userId: "demo-user",
    jobId: "run_failed_api",
    repoName: "fixture/broken-path",
    repoUrl: "local://fixture/broken-path",
    query: "Debug failing import path",
    intent: "debug",
    status: "failed",
    currentNode: null,
    finalOutput: null,
    error: "Repo path does not exist",
    partialSummaries: {},
    errors: [{ node: "supervisor", errorType: "repo_not_found", message: "Repo path does not exist", retryable: false }],
    userCorrections: [],
    verifiedCount: 0,
    unverifiedCount: 0,
    contradictedCount: 0,
    traceUrl: null,
    claimProvenance: [],
    traceMetadata: { agent_name: "supervisor", tool_name: null, mcp_server: null, latency: 0.3, tokens: 0, cost_usd: 0, claim_id: null },
    agentName: "supervisor",
    toolName: null,
    mcpServer: null,
    latency: 0.3,
    tokens: 0,
    costUsd: 0,
    failureModes: ["repo_not_found"],
    createdAt: "2026-06-04T15:40:00Z",
    updatedAt: "2026-06-04T15:40:00Z",
  },
  {
    userId: "demo-user",
    jobId: "run_current_queue",
    repoName: "local/current",
    repoUrl: "local://current",
    query: "Explain current graph runtime",
    intent: "runtime",
    status: "running",
    currentNode: "verifier",
    finalOutput: null,
    error: null,
    partialSummaries: { entry_explainer: "Entry evidence collected; verifier running." },
    errors: [],
    userCorrections: [],
    verifiedCount: 1,
    unverifiedCount: 0,
    contradictedCount: 0,
    traceUrl: "https://smith.langchain.com/",
    claimProvenance: [],
    traceMetadata: { agent_name: "verifier", tool_name: "run_pytest", mcp_server: "test_runner", latency: 6.1, tokens: 0, cost_usd: 0, claim_id: "claim-current" },
    agentName: "verifier",
    toolName: "run_pytest",
    mcpServer: "test_runner",
    latency: 6.1,
    tokens: 0,
    costUsd: 0,
    failureModes: [],
    createdAt: "2026-06-04T15:30:00Z",
    updatedAt: "2026-06-04T15:30:06Z",
  },
];
